from django.db import models

class Summoner (models.Model):
    summoner_id = models.CharField(max_length=255)
    puuid = models.CharField(max_length=255, default=None)
    summoner_name = models.CharField(max_length=255, default=None)
    summoner_tag = models.CharField(max_length=255, default=None)
    region = models.CharField(max_length=30, default=None)
    league_points = models.IntegerField (verbose_name= 'ranked points', default=None)
    total_wins = models.IntegerField (verbose_name= 'total wins', default=None)
    total_losses = models.IntegerField (verbose_name= 'total losses', default=None)
    rank = models.CharField(max_length=255, default=None)
    tier = models.CharField(max_length=255, default=None)

class Match (models.Model):
    summoner_id = models.ForeignKey(Summoner, on_delete=models.CASCADE)
    api_match_id = models.CharField(max_length=255)

class Graphic_data (models.Model):
    summoner_id = models.ForeignKey(Summoner, on_delete=models.CASCADE)
    match_id = models.ForeignKey(Match, on_delete=models.CASCADE)
    kills = models.IntegerField (verbose_name= 'asesinatos del jugador', default=None)
    deaths = models.IntegerField (verbose_name= 'muertes del jugador', default=None)
    assists = models.IntegerField (verbose_name= 'asistencias del jugador', default=None)
    championId = models.IntegerField (verbose_name= 'id del campeón', default=None)
    championName = models.CharField(max_length=255, default=None)
    goldEarned = models.IntegerField (verbose_name= 'oro ganado', default=None)
    goldSpent = models.IntegerField (verbose_name= 'oro gastado', default=None)
    totalDamageDealt = models.IntegerField (verbose_name= 'daño total', default=None)
    totalDamageTaken = models.IntegerField (verbose_name= 'daño total recibido', default=None)
    totalHeal = models.IntegerField (verbose_name= 'curación total', default=None)
    totalHealsOnTeammates = models.IntegerField (verbose_name= 'curación total en compañeros', default=None)
    totalMinionsKilled = models.IntegerField (verbose_name= 'miniones matados', default=None)
    totalTimeSpentDead = models.IntegerField (verbose_name= 'tiempo perdido muerto', default=None)
    totalUnitsHealed = models.IntegerField (verbose_name= 'unidades curadas', default=None)
    visionScore = models.IntegerField (verbose_name= 'puntuación de visión', default=None)
    wardKilled = models.IntegerField (verbose_name= 'ward matado', default=None)
    wardPlaced = models.IntegerField (verbose_name= 'ward colocado', default=None)
    role = models.CharField(max_length=255, default=None)
    lane = models.CharField(max_length=255, default=None)
    participantId = models.IntegerField (verbose_name= 'id del participante', default=None)
    doubleKills = models.IntegerField (verbose_name= 'doble kills', default=None)
    tripleKills = models.IntegerField (verbose_name= 'triple kills', default=None)
    firstBloodAssist = models.BooleanField (verbose_name= 'asistencia de primer asesinato', default=None)
    firstBloodKill = models.BooleanField (verbose_name= 'primer asesinato', default=None)
    win = models.BooleanField (verbose_name= 'victoria', default=None)
    timePlayed = models.IntegerField (verbose_name= 'tiempo jugado', default=None)
    spell1Casts = models.IntegerField (verbose_name= 'primer hechizo', default=None)
    spell2Casts = models.IntegerField (verbose_name= 'segundo hechizo', default=None)
    spell3Casts = models.IntegerField (verbose_name= 'tercer hechizo', default=None)
    spell4Casts = models.IntegerField (verbose_name= 'cuarto hechizo', default=None)
    longestTimeSpentLiving = models.IntegerField (verbose_name= 'tiempo más largo vivido', default=None)
    killingSprees = models.IntegerField (verbose_name= 'asesinatos doble', default=None)
    individualPosition = models.CharField(max_length=255, default=None)
    gameEndedInEarlySurrender = models.BooleanField (verbose_name= 'juego con rendición temprana', default=None)
    gameEndedInSurrender = models.BooleanField (verbose_name= 'juego con rendición', default=None)

class Time_info (models.Model):
    match_id = models.ForeignKey(Match, on_delete=models.CASCADE)
    minute = models.IntegerField(verbose_name='minuto de la partida', default=None)
    damageDone = models.IntegerField(verbose_name= 'daño hecho', default=None)
    damageTaken = models.IntegerField(verbose_name= 'daño tomado', default=None)
    gold = models.IntegerField(verbose_name= 'oro', default=None)
    xp = models.IntegerField(verbose_name= 'xp', default=None)
    minions = models.IntegerField(verbose_name= 'farm', default=None)
    level = models.IntegerField(verbose_name= 'nivel', default=None)

