# Generated by Django 5.0.4 on 2024-04-17 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=255)),
                ('api_summoner_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.CharField(max_length=255)),
                ('summoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
                ('summoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.summoner')),
            ],
        ),
    ]
