# Generated by Django 5.0.4 on 2024-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_summoner_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='api_summoner_id',
            new_name='summoner_id',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='experience',
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='championId',
            field=models.IntegerField(default=None, verbose_name='id del campeón'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='championName',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='doubleKills',
            field=models.IntegerField(default=None, verbose_name='doble kills'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='firstBloodAssist',
            field=models.IntegerField(default=None, verbose_name='asistencia de primer asesinato'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='firstBloodKill',
            field=models.IntegerField(default=None, verbose_name='primer asesinato'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='gameEndedInEarlySurrender',
            field=models.BooleanField(default=None, verbose_name='juego con rendición temprana'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='gameEndedInSurrender',
            field=models.BooleanField(default=None, verbose_name='juego con rendición'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='goldEarned',
            field=models.IntegerField(default=None, verbose_name='oro ganado'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='goldSpent',
            field=models.IntegerField(default=None, verbose_name='oro gastado'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='individualPosition',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='killingSprees',
            field=models.IntegerField(default=None, verbose_name='asesinatos doble'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='lane',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='longestTimeSpentLiving',
            field=models.IntegerField(default=None, verbose_name='tiempo más largo vivido'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='participantId',
            field=models.IntegerField(default=None, verbose_name='id del participante'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='role',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='spell1Casts',
            field=models.IntegerField(default=None, verbose_name='primer hechizo'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='spell2Casts',
            field=models.IntegerField(default=None, verbose_name='segundo hechizo'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='spell3Casts',
            field=models.IntegerField(default=None, verbose_name='tercer hechizo'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='spell4Casts',
            field=models.IntegerField(default=None, verbose_name='cuarto hechizo'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='timePlayed',
            field=models.IntegerField(default=None, verbose_name='tiempo jugado'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalDamageDealt',
            field=models.IntegerField(default=None, verbose_name='daño total'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalDamageTaken',
            field=models.IntegerField(default=None, verbose_name='daño total recibido'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalHeal',
            field=models.IntegerField(default=None, verbose_name='curación total'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalHealsOnTeammates',
            field=models.IntegerField(default=None, verbose_name='curación total en compañeros'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalMinionsKilled',
            field=models.IntegerField(default=None, verbose_name='miniones matados'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalTimeSpentDead',
            field=models.IntegerField(default=None, verbose_name='tiempo perdido muerto'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='totalUnitsHealed',
            field=models.IntegerField(default=None, verbose_name='unidades curadas'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='tripleKills',
            field=models.IntegerField(default=None, verbose_name='triple kills'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='visionScore',
            field=models.IntegerField(default=None, verbose_name='puntuación de visión'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='wardKilled',
            field=models.IntegerField(default=None, verbose_name='ward matado'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='wardPlaced',
            field=models.IntegerField(default=None, verbose_name='ward colocado'),
        ),
        migrations.AddField(
            model_name='graphic_data',
            name='win',
            field=models.BooleanField(default=None, verbose_name='victoria'),
        ),
        migrations.AddField(
            model_name='summoner',
            name='league_points',
            field=models.IntegerField(default=None, verbose_name='ranked points'),
        ),
        migrations.AddField(
            model_name='summoner',
            name='rank',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_tag',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='tier',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='total_losses',
            field=models.IntegerField(default=None, verbose_name='total losses'),
        ),
        migrations.AddField(
            model_name='summoner',
            name='total_wins',
            field=models.IntegerField(default=None, verbose_name='total wins'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='puuid',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
