# Generated by Django 5.0.4 on 2024-04-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_api_summoner_id_summoner_summoner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic_data',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='gold',
        ),
    ]
