# Generated by Django 5.0.4 on 2024-05-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_graphic_data_damage_remove_graphic_data_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(default=None, verbose_name='minuto de la partida')),
                ('damageDone', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('damageTaken', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('gold', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('xp', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('minions', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('level', models.IntegerField(default=None, verbose_name='daño hecho al minuto')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
            ],
        ),
    ]
