# Generated by Django 5.0.4 on 2024-05-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_time_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_data',
            name='firstBloodAssist',
            field=models.BooleanField(default=None, verbose_name='asistencia de primer asesinato'),
        ),
        migrations.AlterField(
            model_name='graphic_data',
            name='firstBloodKill',
            field=models.BooleanField(default=None, verbose_name='primer asesinato'),
        ),
    ]
