# Generated by Django 5.0.4 on 2024-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_graphic_data_firstbloodassist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic_data',
            name='championId',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='doubleKills',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='firstBloodAssist',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='firstBloodKill',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='gameEndedInEarlySurrender',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='gameEndedInSurrender',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='goldSpent',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='individualPosition',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='killingSprees',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='longestTimeSpentLiving',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='participantId',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='spell1Casts',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='spell2Casts',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='spell3Casts',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='spell4Casts',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='timePlayed',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='totalHeal',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='totalHealsOnTeammates',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='totalMinionsKilled',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='totalTimeSpentDead',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='totalUnitsHealed',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='tripleKills',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='visionScore',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='wardKilled',
        ),
        migrations.RemoveField(
            model_name='graphic_data',
            name='wardPlaced',
        ),
        migrations.AlterField(
            model_name='time_info',
            name='damageDone',
            field=models.IntegerField(default=None, verbose_name='daño hecho'),
        ),
        migrations.AlterField(
            model_name='time_info',
            name='damageTaken',
            field=models.IntegerField(default=None, verbose_name='daño tomado'),
        ),
        migrations.AlterField(
            model_name='time_info',
            name='gold',
            field=models.IntegerField(default=None, verbose_name='oro'),
        ),
        migrations.AlterField(
            model_name='time_info',
            name='level',
            field=models.IntegerField(default=None, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='time_info',
            name='minions',
            field=models.IntegerField(default=None, verbose_name='farm'),
        ),
        migrations.AlterField(
            model_name='time_info',
            name='xp',
            field=models.IntegerField(default=None, verbose_name='xp'),
        ),
    ]
