# Generated by Django 5.0.4 on 2024-06-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_graphic_data_championid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_info',
            name='summoner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.summoner'),
        ),
    ]
