# Generated by Django 5.0.6 on 2024-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_summoner_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='server',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
